### ISSUE TITLE
Organizations names with "/" fails in ages analysis (Debian GNU/Linux)

### ISSUE THREAD

**Issue by acs** [VizGrimoire/GrimoireLib#55]
When generating the JSON files with ages (demographics) information for organization, if the name of the organization includes "/" it fails. This "/" should be changed to "_" like in other places.

2015-03-21 13:02:38,025 Analyzing aging for SCM
Traceback (most recent call last):
  File "./report_tool.py", line 361, in <module>
    create_reports_filters(period, startdate, enddate, opts.destdir, opts.npeople, identities_db)
  File "./report_tool.py", line 83, in create_reports_filters
    ds.create_filter_report(filter_, period, startdate, enddate, destdir, npeople, identities_db)
  File "/data/home/owl/automator/automatic_retrieval/mediawiki/tools/GrimoireLib/vizGrimoireJS/vizgrimoire/SCM.py", line 356, in create_filter_report
    startdate, enddate, destdir)
  File "/data/home/owl/automator/automatic_retrieval/mediawiki/tools/GrimoireLib/vizGrimoireJS/vizgrimoire/SCM.py", line 299, in ages_study_com
    res = obj.create_report(ds, destdir)
  File "/data/home/owl/automator/automatic_retrieval/mediawiki/tools/GrimoireLib/vizGrimoireJS/vizgrimoire/analysis/ages.py", line 291, in create_report
    produce_json (file_birth, demos["birth"])
  File "/data/home/owl/automator/automatic_retrieval/mediawiki/tools/GrimoireLib/vizGrimoireJS/vizgrimoire/analysis/ages.py", line 76, in produce_json
    with codecs.open(filename, "w", "utf-8") as file:
  File "/usr/lib/python2.7/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '../../../json/Debian GNU/Linux-scm-com-demographics-birth.json'

**Comment by jgbarah** [comment]
Thanks for reporting. I'm at it...
